main: fr.will33.dodgeball.Dodgeball
name: Dodgeball
version: ${project.version}
api-version: "1.20"
author: William AVENTIN
website: "https://www.elesia.org"
commands:
  config:
    description: "Configurer l'arène"
  join:
    description: "Rejoindre la partie"
  dodgeball:
    description: "Démarrer/Arrêter la partie"